/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_vine_android_recorder_Processor */

#ifndef _Included_co_vine_android_recorder_Processor
#define _Included_co_vine_android_recorder_Processor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_vine_android_recorder_Processor
 * Method:    run
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_co_vine_android_recorder_Processor_run
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif